/*
Nama    : Paramadina Mulya Majid
Stambuk : 13020180006
Tgl/Hari : Senin, 10 Mei 2020
Waktu   : 15.32 WITA
*/
package tugas10;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.util.*; 
import java.util.logging.*; 
import javax.swing.*; 
import javax.swing.event.*; 
import javax.swing.plaf.nimbus.NimbusLookAndFeel; 
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ACER
 */
public class SistemAkademikk extends javax.swing.JFrame {
    List record = new ArrayList();
    InterfaceMahasiswa mhsServis; 
    int row;
    String kFak, kThn;

    public SistemAkademikk() {
        initComponents();
        mhsServis = new ImplementMahasiswa();

        jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) { 
                row = jTable1.getSelectedRow(); 
                if (row != -1) { 
                    isiText(); 
                }
            }
        }); 
        this.statusAwal(); 
        daftarKode(); 
    }
    void daftarKode() { 
        Object[] fak = {"130", "145"}; 
        Object[] thn = {"2012", "2013", "2014", "2015", "2016", "2017", "2018"}; 
        for (int i = 0; i < fak.length; i++) { 
            CbKodeFak.addItem(fak[i].toString()); 
        } 
        kFak = CbKodeFak.getSelectedItem().toString(); 
        for (int i = 0; i < thn.length; i++) { 
            CbThn.addItem(thn[i].toString()); 
        } 
        kThn = CbThn.getSelectedItem().toString(); 
    }
    void loadData() { 
        try { 
            record = mhsServis.getAll(); 
        } catch (SQLException ex) { 
            Logger.getLogger(SistemAkademikk.class.getName()).log(Level.SEVERE, null, ex); 
        } 
    }
    void statusAwal() { 
        kosongkanText(); 
        loadData(); 
        isiTabel(); 
    }
    void kosongkanText() { 
            txtNim.setText(""); 
            txtNama.setText(""); 
            txtAlamat.setText(""); 
    }
 
    void isiTabel() { 
        Object data[][] = new Object[record.size()][3]; 
        int x = 0; 
        for (Iterator it = record.iterator(); it.hasNext();) { 
            Mahasiswa mhs = (Mahasiswa) it.next(); 
            data[x][0] = mhs.getNim(); 
            data[x][1] = mhs.getNama(); 
            data[x][2] = mhs.getAlamat(); 
            x++; 
        } 
        String judul[] = {"NIM", "NAMA", "ALAMAT"}; 
        jTable1.setModel(new DefaultTableModel(data, judul)); 
        jScrollPane1.setViewportView(jTable1); 
    }
    void isiText(){
        Mahasiswa mhs = (Mahasiswa) record.get(row);
        txtNim.setText(mhs.getNim());
        txtNim.setEditable(false);
        txtNama.setText(mhs.getNama());
        txtAlamat.setText(mhs.getAlamat());
        CbKodeFak.setVisible(false);
        CbThn.setVisible(false);
        
        BtnSimpan.setText("Aktif");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CbKodeFak = new javax.swing.JComboBox<>();
        CbThn = new javax.swing.JComboBox<>();
        txtNim = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAlamat = new javax.swing.JTextField();
        BtnSimpan = new javax.swing.JButton();
        BtnEdit = new javax.swing.JButton();
        BtnHapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        ketnim = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("NIM");

        CbKodeFak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbKodeFakActionPerformed(evt);
            }
        });

        CbThn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbThnActionPerformed(evt);
            }
        });

        txtNim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNimMouseClicked(evt);
            }
        });
        txtNim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNimKeyTyped(evt);
            }
        });

        jLabel2.setText("Nama");

        jLabel3.setText("Alamat");

        BtnSimpan.setText("Simpan");
        BtnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSimpanActionPerformed(evt);
            }
        });

        BtnEdit.setText("Edit");
        BtnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditActionPerformed(evt);
            }
        });

        BtnHapus.setText("Hapus");
        BtnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHapusActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "NIM", "Nama", "Alamat"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnSimpan)
                                .addGap(18, 18, 18)
                                .addComponent(BtnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnHapus))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CbKodeFak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(CbThn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtNim))
                            .addComponent(txtNama)
                            .addComponent(txtAlamat))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ketnim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CbKodeFak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CbThn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(ketnim))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSimpan)
                    .addComponent(BtnEdit)
                    .addComponent(BtnHapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSimpanActionPerformed
        try { 
            if ("Simpan".equals(this. BtnSimpan.getText())) { 
                Mahasiswa mhs = new Mahasiswa(); 
                mhs.setNim(kFak + kThn + txtNim.getText()); 
                mhs.setNama(txtNama.getText()); 
                mhs.setAlamat(txtAlamat.getText()); 
                mhsServis.insert(mhs); this.statusAwal(); 
                JOptionPane.showMessageDialog(this, "data tersimpan"); 
            } else { 
                txtNim.setEditable(true); 
                CbKodeFak.setVisible(true); 
                CbThn.setVisible(true); 
                BtnSimpan.setText("Simpan"); 
                kosongkanText(); 
            } 
        } catch (SQLException ex) { 
            Logger.getLogger(SistemAkademikk.class.getName()).log(Level.SEVERE, null, ex); 
        } 
    }//GEN-LAST:event_BtnSimpanActionPerformed

    private void BtnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHapusActionPerformed
        try { 
            String nim = txtNim.getText(); 
            mhsServis.delete(nim); 
            this.statusAwal(); 
            JOptionPane.showMessageDialog(this, "data berhasil dihapus"); 
        } catch (SQLException ex) { 
            Logger.getLogger(SistemAkademikk.class.getName()).log(Level.SEVERE, null, ex); 
        }
    }//GEN-LAST:event_BtnHapusActionPerformed

    private void CbKodeFakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbKodeFakActionPerformed
         kFak = CbKodeFak.getSelectedItem().toString(); 
    }//GEN-LAST:event_CbKodeFakActionPerformed

    private void BtnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditActionPerformed
        try { 
            Mahasiswa mhs = new Mahasiswa(); 
            mhs.setNim(txtNim.getText()); 
            mhs.setNama(txtNama.getText()); 
            mhs.setAlamat(txtAlamat.getText()); 
            mhsServis.update(mhs); 
            this.statusAwal(); 
            JOptionPane.showMessageDialog(this, "data berhasil diubah"); 
        } catch (SQLException ex) { 
            Logger.getLogger(SistemAkademikk.class.getName()).log(Level.SEVERE, null, ex); 
        }
    }//GEN-LAST:event_BtnEditActionPerformed

    private void txtNimKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNimKeyTyped
         txtNim.setToolTipText("4 Angka"); 
         if(txtNim.getText().length()>3){ 
            ketnim.setText("4 Angka"); 
            txtNim.setEditable(false); 
        } 
    }//GEN-LAST:event_txtNimKeyTyped

    private void txtNimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNimMouseClicked
        txtNim.setEditable(true); 
        ketnim.setText(null); 
    }//GEN-LAST:event_txtNimMouseClicked

    private void CbThnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbThnActionPerformed
        kThn = CbThn.getSelectedItem().toString();
    }//GEN-LAST:event_CbThnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try { 
            UIManager.setLookAndFeel(new NimbusLookAndFeel()); 
            SwingUtilities.invokeLater(new Runnable() {
                public void run() { 
                    SistemAkademikk form = new SistemAkademikk();
                    form.setLocationRelativeTo(null); 
                    form.setVisible(true); 
                }
            }); 
        } catch (UnsupportedLookAndFeelException ex) { 
            Logger.getLogger(SistemAkademikk.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEdit;
    private javax.swing.JButton BtnHapus;
    private javax.swing.JButton BtnSimpan;
    private javax.swing.JComboBox<String> CbKodeFak;
    private javax.swing.JComboBox<String> CbThn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel ketnim;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNim;
    // End of variables declaration//GEN-END:variables
}
